version: '3.8'

services:
  api:
    image: bitwalker/alpine-elixir-phoenix:latest
    command: mix phx.server
    ports:
      - 8001:4000
    depends_on:
      - db
    volumes:
      - ./mix:/opt/mix
      - ./${APP_NAME}:/opt/app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data

